## Predicting profit of companies

In [1]:
# Importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Importing dataset and extracting the independent and dependent variables
companies = pd.read_csv('D:\Machine Learning Bootcamp/Datasets/1000_Companies.csv')
x = companies.iloc[:,:-1].values
y = companies.iloc[:,4].values

In [3]:
# Viewing Dataset
companies.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
onehotencoder = OneHotEncoder()
x = onehotencoder.fit_transform(x).toarray()
x[:, 3] = labelencoder.fit_transform(x[:, 3])

print(x)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [5]:
print(x[0])

[0. 0. 0. ... 0. 0. 1.]


In [6]:
# Avoiding the dummy variable trap
x = x[:,1:]

In [7]:
# Splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [8]:
# Fitting multiple linear regression to the trining set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [9]:
# Predicting the test set results
y_pred = regressor.predict(x_test)
y_pred

array([119648.63824645, 118265.37432749, 119611.52633182, 118676.67547519,
       118061.01304871, 117893.6772919 , 118404.63110007, 119942.37630382,
       117831.75515567, 119509.30291994, 119372.839152  , 118643.79910695,
       119240.36154921, 118615.68938211, 119089.62244256, 117795.61886426,
       118931.14243637, 119089.62244256, 118611.05650308, 117831.75515567,
       118001.52308799, 120214.31432239, 118676.67547519, 119657.76219614,
       118931.38175896, 119041.56726519, 118275.15759221, 119667.37519383,
       118787.77529348, 119089.62244256, 118245.03755069, 119365.71362438,
       117707.61946034, 118808.83756031, 119373.05600689, 119228.22725224,
       117831.75515567, 118676.67547519, 118676.67547519, 118931.21928408,
       118196.01160427, 119089.62244256, 119267.12807959, 118680.38623202,
       118613.00176189, 118755.55150519, 118673.4680869 , 119402.02080537,
       118633.95285705, 118487.3774405 , 118676.67547519, 118676.67547519,
       118960.143316  , 1

In [10]:
# Calculating the coefficient
print(regressor.coef_)

[-22917.55489546    443.40243654 -23102.39332534 ...   2032.63701448
   1619.69004711    774.7697276 ]


In [11]:
# Calculating the intercept
print(regressor.intercept_)

117056.98542807891


In [12]:
# Calculating the R squared value
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.0042787323259001475